import {
  defineConfig,
  presetAttributify,
  presetIcons,
  presetTypography,
  presetUno,
  transformerDirectives,
  transformerVariantGroup,
} from 'unocss'

export default defineConfig({
  presets: [
    presetUno(),
    presetAttributify(),
    presetIcons({
      warn: true,
    }),
    presetTypography(),
  ],
  transformers: [transformerDirectives(), transformerVariantGroup()],
  safelist: [
    'i-mdi:view-dashboard',
    'i-mdi:account',
    'i-gridicons:notice',
    'i-mdi:file-table-box',
    'text-white',
    'color-#70a1ff',
    'text-#5ab1ef',
    'text-#fa6e86',
    'text-#19d4ae',
    'text-#ffb980',
    'text-#0067a6',
    'text-#c4b4e4',
    'text-#d87a80',
    'text-#9cbbff',
    'text-#d9d0c7',
    'text-#87a997',
    'text-#d49ea2',
    'text-#5b4947',
    'text-#7ba3a8',
    'bg-#5ab1ef',
    'bg-#fa6e86',
    'bg-#19d4ae',
    'bg-#ffb980',
    'bg-#0067a6',
    'bg-#c4b4e4',
    'bg-#d87a80',
    'bg-#9cbbff',
    'bg-#d9d0c7',
    'bg-#87a997',
    'bg-#d49ea2',
    'bg-#5b4947',
    'bg-#7ba3a8',
    'flex!',
    'grayscale',
  ],
  shortcuts: {
    'fcc': 'flex items-center justify-center',
    'whf': 'w-full h-full',
    'fcb': 'flex items-center justify-between',
    'fcee': 'flex items-center justify-evenly',
    'fca': 'flex items-center justify-around',
    'fce': 'flex items-center justify-end',
    'bg-main': 'bg-#1e90ffFF',
    'text-main': 'text-#1e90ffFF',
  },
})
