/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppProvider: typeof import('./../components/AppProvider/src/AppProvider.vue')['default']
    Charts: typeof import('./../components/Charts/src/Charts.vue')['default']
    Header: typeof import('./../components/Table/src/Header.vue')['default']
    LayoutFooter: typeof import('./../components/Layouts/layoutFooter.vue')['default']
    LayoutHeader: typeof import('./../components/Layouts/layoutHeader.vue')['default']
    LayoutSider: typeof import('./../components/Layouts/layoutSider.vue')['default']
    LayoutTab: typeof import('./../components/Layouts/layoutTab.vue')['default']
    LeftMenu: typeof import('./../components/Layouts/leftMenu.vue')['default']
    Loading: typeof import('./../components/Loading/src/Loading.vue')['default']
    MobileMenu: typeof import('./../components/Layouts/mobileMenu.vue')['default']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    Preview: typeof import('./../components/Preview/src/Preview.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Search: typeof import('./../components/Layouts/search.vue')['default']
    SysSetting: typeof import('./../components/Layouts/sysSetting.vue')['default']
    Table: typeof import('./../components/Table/src/Table.vue')['default']
    ToggleTheme: typeof import('./../components/SwitchTheme/src/ToggleTheme.vue')['default']
    TopMenu: typeof import('./../components/Layouts/topMenu.vue')['default']
  }
}
