/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppProvider: typeof import('./../components/AppProvider/src/AppProvider.vue')['default']
    LayoutHeader: typeof import('./../components/Layouts/layoutHeader.vue')['default']
    LayoutSider: typeof import('./../components/Layouts/layoutSider.vue')['default']
    LayoutTab: typeof import('./../components/Layouts/layoutTab.vue')['default']
    LeftMenu: typeof import('./../components/Layouts/leftMenu.vue')['default']
    Loading: typeof import('./../components/Loading/src/Loading.vue')['default']
    MobileMenu: typeof import('./../components/Layouts/mobileMenu.vue')['default']
    NAvatar: typeof import('naive-ui')['NAvatar']
    NButton: typeof import('naive-ui')['NButton']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NDialogProvider: typeof import('naive-ui')['NDialogProvider']
    NDivider: typeof import('naive-ui')['NDivider']
    NDrawer: typeof import('naive-ui')['NDrawer']
    NDrawerContent: typeof import('naive-ui')['NDrawerContent']
    NDropdown: typeof import('naive-ui')['NDropdown']
    NEmpty: typeof import('naive-ui')['NEmpty']
    NGi: typeof import('naive-ui')['NGi']
    NGrid: typeof import('naive-ui')['NGrid']
    NIcon: typeof import('naive-ui')['NIcon']
    NImage: typeof import('naive-ui')['NImage']
    NLayout: typeof import('naive-ui')['NLayout']
    NLayoutContent: typeof import('naive-ui')['NLayoutContent']
    NLayoutHeader: typeof import('naive-ui')['NLayoutHeader']
    NLayoutSider: typeof import('naive-ui')['NLayoutSider']
    NLoadingBarProvider: typeof import('naive-ui')['NLoadingBarProvider']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NNotificationProvider: typeof import('naive-ui')['NNotificationProvider']
    NPopover: typeof import('naive-ui')['NPopover']
    NTooltip: typeof import('naive-ui')['NTooltip']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SwitchTheme: typeof import('./../components/SwitchTheme/src/SwitchTheme.vue')['default']
    SysSetting: typeof import('./../components/Layouts/sysSetting.vue')['default']
    TopMenu: typeof import('./../components/Layouts/topMenu.vue')['default']
  }
}
